const lessonTitle = "一碗汤面";

const lessonData = [
    // ===== 第 1 段 =====
    ["12月31日", "shí èr yuè sān shí yī rì", "December 31st", "31 Disember"],
    ["，", "", "", ""],
    ["也就是", "yě jiù shì", "which is", "iaitu"],
    ["除夕夜", "chú xī yè", "New Year's Eve", "Malam Tahun Baru"],
    ["，", "", "", ""],
    ["日本", "rì běn", "Japan", "Jepun"],
    ["面馆", "miàn guǎn", "noodle restaurant", "kedai mi"],
    ["的", "de", "", ""],
    ["生意", "shēng yì", "business", "perniagaan"],
    ["都会", "dōu huì", "would", "akan"],
    ["特别", "tè bié", "especially", "sangat"],
    ["好", "hǎo", "good", "baik"],
    ["，", "", "", ""],
    ["“", "", "", ""],
    ["北海亭", "běi hǎi tíng", "Beihai Pavilion", "Beihai Pavilion"],
    ["”", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["不例外", "bù lì wài", "no exception", "tidak terkecuali"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["除夕夜", "chú xī yè", "New Year's Eve", "Malam Tahun Baru"],
    ["吃", "chī", "eating", "makan"],
    ["荞面条", "qiáo miàn tiáo", "buckwheat noodles", "mi soba"],
    ["过年", "guò nián", "celebrate the New Year", "sambut Tahun Baru"],
    ["是", "shì", "is", "ialah"],
    ["日本人", "rì běn rén", "Japanese people's", "orang Jepun"],
    ["的", "de", "", ""],
    ["传统习俗", "chuán tǒng xí sú", "traditional custom", "adat tradisi"],
    ["。", "", "", ""],
    ["“", "", "", ""],
    ["北海亭", "běi hǎi tíng", "Beihai Pavilion", "Beihai Pavilion"],
    ["”", "", "", ""],
    ["的", "de", "", ""],
    ["老板", "lǎo bǎn", "boss", "tuan kedai"],
    ["是个", "shì ge", "is a", "ialah seorang"],
    ["憨厚老实", "hān hòu lǎo shi", "honest and simple", "jujur dan sederhana"],
    ["的", "de", "", ""],
    ["人", "rén", "person", "orang"],
    ["，", "", "", ""],
    ["老板娘", "lǎo bǎn niáng", "boss's wife", "isteri tuan kedai"],
    ["则", "zé", "on the other hand", "sebaliknya"],
    ["古道热肠", "gǔ dào rè cháng", "warm-hearted", "baik hati"],
    ["，", "", "", ""],
    ["待人", "dài rén", "treat people", "melayan orang"],
    ["亲切", "qīn qiè", "kind", "mesra"],
    ["。", "", "", ""],
    ["那天晚上", "nà tiān wǎn shàng", "That night", "Malam itu"],
    ["，", "", "", ""],
    ["最后一个", "zuì hòu yī gè", "the last", "yang terakhir"],
    ["客人", "kè rén", "customer", "pelanggan"],
    ["走出", "zǒu chū", "walked out of", "keluar dari"],
    ["面馆", "miàn guǎn", "noodle restaurant", "kedai mi"],
    ["，", "", "", ""],
    ["老板娘", "lǎo bǎn niáng", "the boss's wife", "isteri tuan kedai"],
    ["正打算", "zhèng dǎ suàn", "was about to", "sedang hendak"],
    ["关店", "guān diàn", "close the shop", "tutup kedai"],
    ["的时候", "de shí hòu", "when", "ketika"],
    ["，", "", "", ""],
    ["一个", "yí gè", "a", "seorang"],
    ["女人", "nǚ rén", "woman", "wanita"],
    ["带着", "dài zhe", "with", "membawa"],
    ["两个", "liǎng gè", "two", "dua orang"],
    ["小男孩", "xiǎo nán hái", "little boys", "budak lelaki"],
    ["走进来", "zǒu jìn lái", "walked in", "masuk"],
    ["，", "", "", ""],
    ["两个", "liǎng gè", "two", "dua orang"],
    ["孩子", "hái zi", "children", "anak"],
    ["大约", "dà yuē", "about", "kira-kira"],
    ["是", "shì", "were", "berumur"],
    ["6岁", "liù suì", "6 years old", "6 tahun"],
    ["和", "hé", "and", "dan"],
    ["10岁左右", "shí suì zuǒ yòu", "about 10 years old", "lebih kurang 10 tahun"],
    ["，", "", "", ""],
    ["穿着", "chuān zhe", "wearing", "memakai"],
    ["全新的", "quán xīn de", "brand new", "baharu"],
    ["一模一样的", "yī mú yī yàng de", "identical", "sama"],
    ["运动服", "yùn dòng fú", "sportswear", "pakaian sukan"],
    ["，", "", "", ""],
    ["那女人", "nà nǚ rén", "the woman", "wanita itu"],
    ["却", "què", "however", "namun"],
    ["穿着", "chuān zhe", "wearing", "memakai"],
    ["过时的", "guò shí de", "outdated", "ketinggalan zaman"],
    ["格子", "gé zi", "plaid", "bercorak kotak-kotak"],
    ["旧大衣", "jiù dà yī", "old coat", "kot lama"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 2 段

    ["“", "", "", ""],
    ["请坐", "qǐng zuò", "Please sit", "Sila duduk"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["听", "tīng", "Hearing", "Mendengar"],
    ["老板", "lǎo bǎn", "the boss", "tuan kedai"],
    ["这么", "zhè me", "so", "begitu"],
    ["招呼", "zhāo hu", "greet", "sapa"],
    ["，", "", "", ""],
    ["那个女人", "nà ge nǚ rén", "that woman", "wanita itu"],
    ["怯怯地", "qiè qiè de", "timidly", "dengan segan"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["可不可以", "kě bù kě yǐ", "May I", "Bolehkah"],
    ["……", "", "", ""],
    ["来一碗", "lái yī wǎn", "have a bowl of", "minta semangkuk"],
    ["……", "", "", ""],
    ["汤面", "tāng miàn", "noodle soup", "mi sup"],
    ["？”", "", "", ""],
    ["背后的", "bèi hòu de", "Behind", "Di belakang"],
    ["两个孩子", "liǎng gè hái zi", "the two children", "dua orang anak"],
    ["不安地", "bù ān de", "uneasily", "dengan gelisah"],
    ["对望了", "duì wàng le", "looked at each other", "saling berpandangan"],
    ["一眼", "yì yǎn", "once", "sekejap"],
    ["。", "", "", ""],
    ["“", "", "", ""],
    ["当然", "dāng rán", "Of course", "Tentu"],
    ["……", "", "", ""],
    ["当然可以", "dāng rán kě yǐ", "of course", "tentu boleh"],
    ["，", "", "", ""],
    ["请", "qǐng", "please", "sila"],
    ["这边坐", "zhè biān zuò", "sit over here", "duduk sini"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["老板娘", "lǎo bǎn niáng", "The boss's wife", "Isteri tuan kedai"],
    ["带着", "dài zhe", "led", "membawa"],
    ["他们", "tā men", "them", "mereka"],
    ["走到", "zǒu dào", "walked to", "berjalan ke"],
    ["最靠边的", "zuì kào biān de", "the most corner", "paling tepi"],
    ["二号桌子", "èr hào zhuō zi", "Table No.2", "Meja No.2"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["向", "xiàng", "towards", "ke arah"],
    ["台", "tái", "counter", "kaunter"],
    ["那边", "nà biān", "that side", "sana"],
    ["大声喊着", "dà shēng hǎn zhe", "shouted", "menjerit"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["一碗汤面", "yī wǎn tāng miàn", "One bowl of noodle soup", "Semangkuk mi sup"],
    ["！”", "", "", ""],
    ["一人份", "yī rén fèn", "One portion", "Satu hidangan"],
    ["只有", "zhǐ yǒu", "only has", "hanya ada"],
    ["一团面", "yī tuán miàn", "one portion of noodles", "satu bahagian mi"],
    ["，", "", "", ""],
    ["老板", "lǎo bǎn", "the boss", "tuan kedai"],
    ["多丢了", "duō diū le", "added extra", "tambah"],
    ["半团面", "bàn tuán miàn", "half a portion of noodles", "setengah bahagian mi"],
    ["，", "", "", ""],
    ["煮了", "zhǔ le", "cooked", "masak"],
    ["满满", "mǎn mǎn", "full", "penuh"],
    ["一大碗", "yī dà wǎn", "a big bowl", "semangkuk besar"],
    ["，", "", "", ""],
    ["老板娘", "lǎo bǎn niáng", "the boss's wife", "isteri tuan kedai"],
    ["和", "hé", "and", "dan"],
    ["客人都", "kè rén dōu", "the customers", "pelanggan"],
    ["不知道", "bù zhī dào", "didn't know", "tidak tahu"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 3 段

    ["母子三人", "mǔ zǐ sān rén", "The mother and two sons", "Ibu dan dua anak"],
    ["围着", "wéi zhe", "around", "sekitar"],
    ["一碗汤面", "yī wǎn tāng miàn", "one bowl of noodle soup", "semangkuk mi sup"],
    ["吃得", "chī de", "ate", "makan"],
    ["津津有味", "jīn jīn yǒu wèi", "with relish", "dengan lahap"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["好好吃", "hǎo hǎo chī", "So delicious", "Sangat sedap"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["“", "", "", ""],
    ["妈", "mā", "Mom", "Ibu"],
    ["，", "", "", ""],
    ["您", "nín", "you", "awak"],
    ["也", "yě", "also", "juga"],
    ["吃吃看", "chī chī kàn", "try some", "cuba"],
    ["嘛", "ma", "particle", "!"],
    ["！”", "", "", ""],
    ["弟弟", "dì di", "The younger brother", "Adik"],
    ["说着", "shuō zhe", "said", "sambil berkata"],
    ["，", "", "", ""],
    ["夹了", "jiā le", "picked up", "ambil"],
    ["一根", "yì gēn", "a", "seutas"],
    ["面条", "miàn tiáo", "noodle", "mi"],
    ["往", "wǎng", "towards", "ke"],
    ["母亲", "mǔ qīn", "mother's", "ibu"],
    ["嘴里送", "zuǐ lǐ sòng", "mouth", "mulut"],
    ["。", "", "", ""],
    ["吃完后", "chī wán hòu", "After finishing", "Selepas habis makan"],
    ["，", "", "", ""],
    ["女人", "nǚ rén", "the woman", "wanita itu"],
    ["付了", "fù le", "paid", "bayar"],
    ["一百五十元", "yī bǎi wǔ shí yuán", "150 yen", "150 yen"],
    ["，", "", "", ""],
    ["母子三人", "mǔ zǐ sān rén", "the mother and two sons", "ibu dan dua anak"],
    ["同声", "tóng shēng", "in unison", "serentak"],
    ["夸赞", "kuā zàn", "praised", "memuji"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["真好吃", "zhēn hǎo chī", "Really delicious", "Sungguh sedap"],
    ["，", "", "", ""],
    ["谢谢", "xiè xie", "Thank you", "Terima kasih"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["并且", "bìng qiě", "and", "dan"],
    ["微微地", "wēi wēi de", "slightly", "sedikit"],
    ["鞠了", "jū le", "bowed", "tunduk"],
    ["一躬", "yī gōng", "a bow", "sekali"],
    ["，", "", "", ""],
    ["走出", "zǒu chū", "walked out of", "keluar dari"],
    ["面馆", "miàn guǎn", "noodle restaurant", "kedai mi"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 4 段

    ["“", "", "", ""],
    ["谢谢你们", "xiè xie nǐ men", "Thank you", "Terima kasih"],
    ["！", "", "", ""],
    ["新年快乐", "xīn nián kuài lè", "Happy New Year", "Selamat Tahun Baru"],
    ["！”", "", "", ""],
    ["老板", "lǎo bǎn", "The boss", "Tuan kedai"],
    ["和", "hé", "and", "dan"],
    ["老板娘", "lǎo bǎn niáng", "boss's wife", "isteri tuan kedai"],
    ["同时", "tóng shí", "at the same time", "serentak"],
    ["这么说", "zhè me shuō", "said this", "berkata begitu"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段

    ["每天", "měi tiān", "Every day", "Setiap hari"],
    ["忙着忙着", "máng zhe máng zhe", "busy", "sibuk"],
    ["，", "", "", ""],
    ["不知不觉", "bù zhī bù jué", "unconsciously", "tanpa sedar"],
    ["很快地", "hěn kuài de", "very quickly", "dengan cepat"],
    ["又", "yòu", "again", "lagi"],
    ["过了一年", "guò le yī nián", "passed a year", "berlalu setahun"],
    ["。", "", "", ""],
    ["又", "yòu", "Again", "Lagi"],
    ["到了", "dào le", "arrived at", "tiba di"],
    ["12月31日", "shí èr yuè sān shí yī rì", "December 31st", "31 Disember"],
    ["这一天", "zhè yī tiān", "this day", "hari ini"],
    ["，", "", "", ""],
    ["“", "", "", ""],
    ["北海亭", "běi hǎi tíng", "Beihai Pavilion", "Beihai Pavilion"],
    ["”", "", "", ""],
    ["的", "de", "", ""],
    ["生意", "shēng yì", "business", "perniagaan"],
    ["仍然", "réng rán", "still", "masih"],
    ["非常", "fēi cháng", "very", "sangat"],
    ["兴旺", "xīng wàng", "prosperous", "pesat"],
    ["，", "", "", ""],
    ["比", "bǐ", "than", "daripada"],
    ["去年", "qù nián", "last year", "tahun lepas"],
    ["除夕夜", "chú xī yè", "New Year's Eve", "Malam Tahun Baru"],
    ["更", "gèng", "more", "lebih"],
    ["忙碌", "máng lù", "busy", "sibuk"],
    ["的", "de", "", ""],
    ["一天", "yì tiān", "day", "hari"],
    ["终于", "zhōng yú", "finally", "akhirnya"],
    ["结束了", "jié shù le", "ended", "berakhir"],
    ["，", "", "", ""],
    ["过了", "guò le", "passed", "lepas"],
    ["10点", "shí diǎn", "10 o'clock", "pukul 10"],
    ["，", "", "", ""],
    ["老板娘", "lǎo bǎn niáng", "the boss's wife", "isteri tuan kedai"],
    ["走向", "zǒu xiàng", "walked towards", "berjalan ke"],
    ["店门前", "diàn mén qián", "shop front", "depan kedai"],
    ["，", "", "", ""],
    ["正想", "zhèng xiǎng", "was about to", "sedang hendak"],
    ["将门", "jiāng mén", "the door", "pintu"],
    ["拉下", "lā xià", "pull down", "tutup"],
    ["的时候", "de shí hòu", "when", "ketika"],
    ["，", "", "", ""],
    ["店门外", "diàn mén wài", "outside the shop", "di luar kedai"],
    ["又", "yòu", "again", "lagi"],
    ["走进来了", "zǒu jìn lái le", "walked in", "masuk"],
    ["一个", "yí gè", "a", "seorang"],
    ["中年妇人", "zhōng nián fù rén", "middle-aged woman", "wanita pertengahan umur"],
    ["和", "hé", "and", "dan"],
    ["两个小孩", "liǎng gè xiǎo hái", "two children", "dua orang anak"],
    ["。", "", "", ""],
    ["老板娘", "lǎo bǎn niáng", "The boss's wife", "Isteri tuan kedai"],
    ["看到", "kàn dào", "saw", "melihat"],
    ["那件", "nà jiàn", "that", "itu"],
    ["过时的", "guò shí de", "outdated", "ketinggalan zaman"],
    ["格子旧上衣", "gé zi jiù shàng yī", "plaid old coat", "kot lama berjalur"],
    ["，", "", "", ""],
    ["马上", "mǎ shàng", "immediately", "segera"],
    ["想起", "xiǎng qǐ", "remembered", "teringat"],
    ["一年前", "yī nián qián", "a year ago", "setahun lepas"],
    ["除夕夜", "chú xī yè", "New Year's Eve", "Malam Tahun Baru"],
    ["最后的", "zuì hòu de", "last", "terakhir"],
    ["客人", "kè rén", "customer", "pelanggan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 6 段

    ["“", "", "", ""],
    ["可以不可以", "kě yǐ bù kě yǐ", "May I", "Bolehkah"],
    ["……", "", "", ""],
    ["给我们", "gěi wǒ men", "for us", "untuk kami"],
    ["煮碗", "zhǔ wǎn", "cook a bowl", "masak semangkuk"],
    ["……", "", "", ""],
    ["一碗汤面", "yī wǎn tāng miàn", "one bowl of noodle soup", "semangkuk mi sup"],
    ["？”", "", "", ""],
    ["“", "", "", ""],
    ["当然", "dāng rán", "Of course", "Tentu"],
    ["，", "", "", ""],
    ["当然", "dāng rán", "of course", "tentu"],
    ["，", "", "", ""],
    ["请这边坐", "qǐng zhè biān zuò", "please sit over here", "sila duduk sini"],
    ["！”", "", "", ""],
    ["老板娘", "lǎo bǎn niáng", "The boss's wife", "Isteri tuan kedai"],
    ["一边", "yì biān", "while", "sambil"],
    ["带", "dài", "led", "membawa"],
    ["他们", "tā men", "them", "mereka"],
    ["到", "dào", "to", "ke"],
    ["去年", "qù nián", "last year's", "tahun lepas"],
    ["坐过", "zuò guò", "sat at", "duduk di"],
    ["的", "de", "", ""],
    ["二号桌子", "èr hào zhuō zi", "Table No.2", "Meja No.2"],
    ["，", "", "", ""],
    ["一边", "yì biān", "while", "sambil"],
    ["大声喊", "dà shēng hǎn", "shouted loudly", "jerit"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["一碗汤面", "yī wǎn tāng miàn", "One bowl of noodle soup", "Semangkuk mi sup"],
    ["！”", "", "", ""],
    ["老板", "lǎo bǎn", "The boss", "Tuan kedai"],
    ["一边", "yì biān", "while", "sambil"],
    ["应声", "yìng shēng", "responded", "menjawab"],
    ["，", "", "", ""],
    ["一边", "yì biān", "while", "sambil"],
    ["点上", "diǎn shàng", "lit", "nyalakan"],
    ["刚刚", "gāng gāng", "just", "baru"],
    ["熄掉", "xī diào", "extinguished", "padam"],
    ["的", "de", "", ""],
    ["炉火", "lú huǒ", "stove fire", "api dapur"],
    ["。", "", "", ""],
    ["老板娘", "lǎo bǎn niáng", "The boss's wife", "Isteri tuan kedai"],
    ["偷偷地", "tōu tōu de", "secretly", "secara rahsia"],
    ["在", "zài", "in", "di"],
    ["丈夫", "zhàng fu", "husband's", "suami"],
    ["的", "de", "", ""],
    ["耳朵旁", "ěr duo páng", "ear", "telinga"],
    ["说着", "shuō zhe", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["喂", "wèi", "Hey", "Hey"],
    ["，", "", "", ""],
    ["煮三碗", "zhǔ sān wǎn", "cook three bowls", "masak tiga mangkuk"],
    ["给", "gěi", "for", "untuk"],
    ["他们", "tā men", "them", "mereka"],
    ["吃", "chī", "eat", "makan"],
    ["好不好", "hǎo bù hǎo", "okay", "boleh"],
    ["？”", "", "", ""],
    ["“", "", "", ""],
    ["不行", "bù xíng", "No", "Tidak boleh"],
    ["，", "", "", ""],
    ["这样做", "zhè yàng zuò", "doing this", "buat begini"],
    ["他们", "tā men", "they", "mereka"],
    ["会", "huì", "will", "akan"],
    ["不好意思", "bù hǎo yì si", "feel embarrassed", "malu"],
    ["的", "de", "", ""],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["丈夫", "zhàng fu", "The husband", "Suami"],
    ["一边", "yì biān", "while", "sambil"],
    ["这么", "zhè me", "so", "begitu"],
    ["回答", "huí dá", "answered", "menjawab"],
    ["，", "", "", ""],
    ["一边", "yì biān", "while", "sambil"],
    ["多丢进", "duō diū jìn", "added extra", "tambah"],
    ["半团面", "bàn tuán miàn", "half a portion of noodles", "setengah bahagian mi"],
    ["到", "dào", "into", "ke"],
    ["滚烫的", "gǔn tàng de", "boiling", "mendidih"],
    ["锅子里", "guō zi lǐ", "pot", "periuk"],
    ["。", "", "", ""],
    ["老板", "lǎo bǎn", "The boss", "Tuan kedai"],
    ["默默地", "mò mò de", "silently", "dengan senyap"],
    ["盛好", "chéng hǎo", "served", "sedia"],
    ["一大碗", "yī dà wǎn", "a big bowl", "semangkuk besar"],
    ["香喷喷的", "xiāng pēn pēn de", "fragrant", "wangi"],
    ["面", "miàn", "noodles", "mi"],
    ["交给", "jiāo gěi", "handed over to", "serahkan kepada"],
    ["妻子", "qī zi", "wife", "isteri"],
    ["端出去", "duān chū qù", "carry out", "bawa keluar"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 7 段

    ["“", "", "", ""],
    ["好香", "hǎo xiāng", "So fragrant", "Sangat wangi"],
    ["……", "", "", ""],
    ["好棒", "hǎo bàng", "Great", "Sungguh baik"],
    ["……", "", "", ""],
    ["真好吃", "zhēn hǎo chī", "Really delicious", "Sungguh sedap"],
    ["……", "", "", ""],
    ["”", "", "", ""],
    ["“", "", "", ""],
    ["今年", "jīn nián", "This year", "Tahun ini"],
    ["还能", "hái néng", "still can", "masih boleh"],
    ["吃到", "chī dào", "eat", "makan"],
    ["“", "", "", ""],
    ["北海亭", "běi hǎi tíng", "Beihai Pavilion", "Beihai Pavilion"],
    ["”", "", "", ""],
    ["的", "de", "", ""],
    ["面", "miàn", "noodles", "mi"],
    ["，", "", "", ""],
    ["真不错", "zhēn bú cuò", "really good", "sungguh baik"],
    ["！”", "", "", ""],
    ["“", "", "", ""],
    ["明年", "míng nián", "Next year", "Tahun depan"],
    ["能够", "néng gòu", "can", "boleh"],
    ["再来", "zài lái", "come again", "datang lagi"],
    ["吃", "chī", "eat", "makan"],
    ["，", "", "", ""],
    ["就好了", "jiù hǎo le", "that would be great", "baguslah"],
    ["！”", "", "", ""],
    ["吃完后", "chī wán hòu", "After finishing", "Selepas habis makan"],
    ["，", "", "", ""],
    ["女人", "nǚ rén", "the woman", "wanita itu"],
    ["付了", "fù le", "paid", "bayar"],
    ["一百五十元", "yī bǎi wǔ shí yuán", "150 yen", "150 yen"],
    ["，", "", "", ""],
    ["母子三人", "mǔ zǐ sān rén", "the mother and two sons", "ibu dan dua anak"],
    ["又", "yòu", "again", "lagi"],
    ["走出了", "zǒu chū le", "walked out of", "keluar dari"],
    ["“", "", "", ""],
    ["北海亭", "běi hǎi tíng", "Beihai Pavilion", "Beihai Pavilion"],
    ["”", "", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 8 段

    ["“", "", "", ""],
    ["谢谢", "xiè xie", "Thank you", "Terima kasih"],
    ["！", "", "", ""],
    ["祝你们", "zhù nǐ men", "Wish you", "Selamat"],
    ["新年快乐", "xīn nián kuài lè", "Happy New Year", "Tahun Baru"],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 9 段

    ["第三年", "dì sān nián", "The third year", "Tahun ketiga"],
    ["的", "de", "", ""],
    ["除夕夜", "chú xī yè", "New Year's Eve", "Malam Tahun Baru"],
    ["，", "", "", ""],
    ["“", "", "", ""],
    ["北海亭", "běi hǎi tíng", "Beihai Pavilion", "Beihai Pavilion"],
    ["”", "", "", ""],
    ["的", "de", "", ""],
    ["生意", "shēng yì", "business", "perniagaan"],
    ["仍然", "réng rán", "still", "masih"],
    ["非常", "fēi cháng", "very", "sangat"],
    ["好", "hǎo", "good", "baik"],
    ["。", "", "", ""],
    ["10点到了", "shí diǎn dào le", "10 o'clock arrived", "Pukul 10 tiba"],
    ["，", "", "", ""],
    ["老板", "lǎo bǎn", "the boss", "tuan kedai"],
    ["急忙", "jí máng", "hurriedly", "segera"],
    ["将", "jiāng", "to", "untuk"],
    ["墙壁上", "qiáng bì shàng", "on the wall", "di dinding"],
    ["的", "de", "", ""],
    ["价目表", "jià mù biǎo", "price list", "senarai harga"],
    ["一张一张", "yì zhāng yì zhāng", "one by one", "sehelai demi sehelai"],
    ["往里翻", "wǎng lǐ fān", "turned inward", "pusing ke dalam"],
    ["，", "", "", ""],
    ["把", "bǎ", "to", "untuk"],
    ["今年夏天", "jīn nián xià tiān", "this summer", "musim panas ini"],
    ["涨价的", "zhǎng jià de", "price increase", "kenaikan harga"],
    ["“", "", "", ""],
    ["汤面一碗二百元", "tāng miàn yī wǎn èr bǎi yuán", "200 yen per bowl", "200 yen semangkuk"],
    ["”", "", "", ""],
    ["那张", "nà zhāng", "that", "itu"],
    ["价目表", "jià mù biǎo", "price list", "senarai harga"],
    ["，", "", "", ""],
    ["重新", "chóng xīn", "again", "semula"],
    ["写上", "xiě shàng", "wrote", "tulis"],
    ["一百五十元", "yī bǎi wǔ shí yuán", "150 yen", "150 yen"],
    ["。", "", "", ""],
    ["二号桌上面", "èr hào zhuō shàng miàn", "On Table No.2", "Di atas Meja No.2"],
    ["，", "", "", ""],
    ["30分钟前", "sān shí fēn zhōng qián", "30 minutes earlier", "30 minit sebelumnya"],
    ["老板娘", "lǎo bǎn niáng", "the boss's wife", "isteri tuan kedai"],
    ["就先", "jiù xiān", "first", "telah"],
    ["放上", "fàng shàng", "placed", "letakkan"],
    ["一张", "yì zhāng", "a", "sehelai"],
    ["“", "", "", ""],
    ["预约席", "yù yuē xí", "Reserved", "Tempat Simpanan"],
    ["”", "", "", ""],
    ["的", "de", "", ""],
    ["卡片", "kǎ piàn", "card", "kad"],
    ["。", "", "", ""],
    ["10点半的时候", "shí diǎn bàn de shí hòu", "At 10:30", "Pada pukul 10:30"],
    ["，", "", "", ""],
    ["这对", "zhè duì", "this", "ini"],
    ["母子三人", "mǔ zǐ sān rén", "mother and two sons", "ibu dan dua anak"],
    ["终于", "zhōng yú", "finally", "akhirnya"],
    ["又", "yòu", "again", "lagi"],
    ["出现了", "chū xiàn le", "appeared", "muncul"],
    ["。", "", "", ""],
    ["哥哥", "gē ge", "The older brother", "Abang"],
    ["穿着", "chuān zhe", "wearing", "memakai"],
    ["国中", "guó zhōng", "junior high school", "sekolah menengah rendah"],
    ["的", "de", "", ""],
    ["制服", "zhì fú", "uniform", "uniform"],
    ["，", "", "", ""],
    ["弟弟", "dì di", "the younger brother", "adik"],
    ["穿着", "chuān zhe", "wearing", "memakai"],
    ["去年", "qù nián", "last year's", "tahun lepas"],
    ["哥哥", "gē ge", "brother's", "abang"],
    ["穿过", "chuān guò", "worn", "pakai"],
    ["的", "de", "", ""],
    ["稍嫌", "shāo xián", "a bit too", "agak"],
    ["大一点", "dà yī diǎn", "a little big", "besar sedikit"],
    ["的", "de", "", ""],
    ["夹克", "jiá kè", "jacket", "jaket"],
    ["，", "", "", ""],
    ["两个", "liǎng gè", "two", "dua orang"],
    ["孩子", "hái zi", "children", "anak"],
    ["都", "dōu", "both", "kedua-duanya"],
    ["长大", "zhǎng dà", "grown", "besar"],
    ["很多", "hěn duō", "a lot", "banyak"],
    ["，", "", "", ""],
    ["母亲", "mǔ qīn", "mother", "ibu"],
    ["仍然", "réng rán", "still", "masih"],
    ["穿着", "chuān zhe", "wearing", "memakai"],
    ["那件", "nà jiàn", "that", "itu"],
    ["褪了色", "tuì le sè", "faded", "luntur"],
    ["的", "de", "", ""],
    ["格子布", "gé zi bù", "plaid fabric", "kain berjalur"],
    ["旧大衣", "jiù dà yī", "old coat", "kot lama"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 10 段

    ["“", "", "", ""],
    ["请进", "qǐng jìn", "Please come in", "Sila masuk"],
    ["！", "", "", ""],
    ["请进", "qǐng jìn", "Please come in", "Sila masuk"],
    ["！”", "", "", ""],
    ["老板娘", "lǎo bǎn niáng", "The boss's wife", "Isteri tuan kedai"],
    ["热情地", "rè qíng de", "warmly", "dengan mesra"],
    ["招呼着", "zhāo hu zhe", "greeted", "menyapa"],
    ["。", "", "", ""],
    ["望着", "wàng zhe", "Looking at", "Memandang"],
    ["笑脸相迎", "xiào liǎn xiāng yíng", "smiling faces", "wajah tersenyum"],
    ["的", "de", "", ""],
    ["老板娘", "lǎo bǎn niáng", "boss's wife", "isteri tuan kedai"],
    ["，", "", "", ""],
    ["母亲", "mǔ qīn", "mother", "ibu"],
    ["战战兢兢地", "zhàn zhàn jīng jīng de", "timidly", "dengan segan"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["麻烦", "má fan", "Sorry to trouble you", "Maaf menyusahkan"],
    ["……", "", "", ""],
    ["麻烦", "má fan", "trouble", "menyusahkan"],
    ["煮", "zhǔ", "cook", "masak"],
    ["两碗汤面", "liǎng wǎn tāng miàn", "two bowls of noodle soup", "dua mangkuk mi sup"],
    ["好不好", "hǎo bù hǎo", "okay", "boleh"],
    ["？”", "", "", ""],
    ["“", "", "", ""],
    ["好的", "hǎo de", "Okay", "Baik"],
    ["，", "", "", ""],
    ["请这边坐", "qǐng zhè biān zuò", "please sit over here", "sila duduk sini"],
    ["！”", "", "", ""],
    ["老板娘", "lǎo bǎn niáng", "The boss's wife", "Isteri tuan kedai"],
    ["招待", "zhāo dài", "ushered", "menjemput"],
    ["他们", "tā men", "them", "mereka"],
    ["坐到", "zuò dào", "sit at", "duduk di"],
    ["二号桌", "èr hào zhuō", "Table No.2", "Meja No.2"],
    ["，", "", "", ""],
    ["赶快", "gǎn kuài", "quickly", "segera"],
    ["若无其事地", "ruò wú qí shì de", "as if nothing happened", "seolah-olah tiada apa"],
    ["将", "jiāng", "to", "untuk"],
    ["那", "nà", "that", "itu"],
    ["“", "", "", ""],
    ["预约席", "yù yuē xí", "Reserved", "Tempat Simpanan"],
    ["”", "", "", ""],
    ["的", "de", "", ""],
    ["卡片", "kǎ piàn", "card", "kad"],
    ["藏起来", "cáng qǐ lái", "hid", "sembunyi"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["向", "xiàng", "towards", "ke arah"],
    ["里面", "lǐ miàn", "inside", "dalam"],
    ["喊着", "hǎn zhe", "shouted", "jerit"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["两碗汤面", "liǎng wǎn tāng miàn", "Two bowls of noodle soup", "Dua mangkuk mi sup"],
    ["！”", "", "", ""],
    ["“", "", "", ""],
    ["是的", "shì de", "Yes", "Ya"],
    ["！", "", "", ""],
    ["两碗汤面", "liǎng wǎn tāng miàn", "Two bowls of noodle soup", "Dua mangkuk mi sup"],
    ["！", "", "", ""],
    ["马上就好了", "mǎ shàng jiù hǎo le", "Coming right up", "Sebentar lagi"],
    ["！”", "", "", ""],
    ["老板", "lǎo bǎn", "The boss", "Tuan kedai"],
    ["一边", "yì biān", "while", "sambil"],
    ["应声", "yìng shēng", "responded", "menjawab"],
    ["，", "", "", ""],
    ["一边", "yì biān", "while", "sambil"],
    ["丢进了", "diū jìn le", "added", "masukkan"],
    ["三团面", "sān tuán miàn", "three portions of noodles", "tiga bahagian mi"],
    ["进去", "jìn qù", "in", "ke dalam"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 11 段

    ["母子三人", "mǔ zǐ sān rén", "The mother and two sons", "Ibu dan dua anak"],
    ["一边", "yì biān", "while", "sambil"],
    ["吃面", "chī miàn", "eating noodles", "makan mi"],
    ["，", "", "", ""],
    ["一边", "yì biān", "while", "sambil"],
    ["谈着话", "tán zhe huà", "talking", "berbual"],
    ["，", "", "", ""],
    ["看起来", "kàn qǐ lái", "looked", "kelihatan"],
    ["很高兴", "hěn gāo xìng", "very happy", "sangat gembira"],
    ["的样子", "de yàng zi", "seemed", "rupanya"],
    ["。", "", "", ""],
    ["站在", "zhàn zài", "Standing", "Berdiri di"],
    ["厨台后面", "chú tái hòu miàn", "behind the kitchen counter", "belakang kaunter dapur"],
    ["的", "de", "", ""],
    ["老板夫妇", "lǎo bǎn fū fù", "the boss and his wife", "pasangan tuan kedai"],
    ["内心", "nèi xīn", "hearts", "hati"],
    ["也", "yě", "also", "juga"],
    ["跟着", "gēn zhe", "also", "turut"],
    ["喜悦", "xǐ yuè", "joyful", "gembira"],
    ["起来", "qǐ lái", "became", "menjadi"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 12 段

    ["“", "", "", ""],
    ["小淳", "xiǎo chún", "Xiaochun", "Xiaochun"],
    ["和哥哥", "hé gē ge", "and brother", "dan abang"],
    ["，", "", "", ""],
    ["妈妈", "mā ma", "Mom", "Ibu"],
    ["今天", "jīn tiān", "today", "hari ini"],
    ["要", "yào", "want to", "hendak"],
    ["谢谢", "xiè xie", "thank", "berterima kasih"],
    ["你们", "nǐ men", "you two", "kamu"],
    ["两个人啊", "liǎng gè rén a", "both of you", "dua orang"],
    ["！", "", "", ""],
    ["你们", "nǐ men", "Your", "Kamu punya"],
    ["过世的", "guò shì de", "deceased", "arwah"],
    ["爸爸", "bà ba", "father", "ayah"],
    ["所造成", "suǒ zào chéng", "caused", "menyebabkan"],
    ["八个人", "bā gè rén", "eight people", "lapan orang"],
    ["受伤", "shòu shāng", "injured", "cedera"],
    ["的", "de", "", ""],
    ["车祸", "chē huò", "car accident", "kemalangan jalan raya"],
    ["，", "", "", ""],
    ["保险公司", "bǎo xiǎn gōng sī", "Insurance company", "Syarikat insurans"],
    ["不能", "bù néng", "cannot", "tidak dapat"],
    ["支付", "zhī fù", "pay", "bayar"],
    ["的", "de", "", ""],
    ["部分", "bù fen", "part", "bahagian"],
    ["，", "", "", ""],
    ["这几年", "zhè jǐ nián", "these few years", "beberapa tahun ini"],
    ["来", "lái", "since", "sejak"],
    ["每个月", "měi gè yuè", "every month", "setiap bulan"],
    ["都", "dōu", "have to", "perlu"],
    ["必须", "bì xū", "must", "perlu"],
    ["缴", "jiǎo", "pay", "bayar"],
    ["五万元", "wǔ wàn yuán", "50,000 yen", "50,000 yen"],
    ["。", "", "", ""],
    ["本来", "běn lái", "Originally", "Pada asalnya"],
    ["应该", "yīng gāi", "should", "patut"],
    ["缴到", "jiǎo dào", "pay until", "bayar sehingga"],
    ["明年三月", "míng nián sān yuè", "March next year", "Mac tahun depan"],
    ["的", "de", "", ""],
    ["，", "", "", ""],
    ["但是", "dàn shì", "but", "tetapi"],
    ["今天", "jīn tiān", "today", "hari ini"],
    ["已", "yǐ", "already", "telah"],
    ["全数", "quán shù", "in full", "sepenuhnya"],
    ["缴完了", "jiǎo wán le", "paid off", "selesai bayar"],
    ["！”", "", "", ""],
    ["“", "", "", ""],
    ["哦", "ó", "Oh", "Oh"],
    ["，", "", "", ""],
    ["妈妈", "mā ma", "Mom", "Ibu"],
    ["，", "", "", ""],
    ["真的吗", "zhēn de ma", "really", "benarkah"],
    ["？”", "", "", ""],
    ["“", "", "", ""],
    ["真的", "zhēn de", "Really", "Benar"],
    ["。", "", "", ""],
    ["因为", "yīn wèi", "Because", "Kerana"],
    ["哥哥", "gē ge", "brother", "abang"],
    ["认真地", "rèn zhēn de", "diligently", "dengan tekun"],
    ["送报", "sòng bào", "delivered newspapers", "hantar surat khabar"],
    ["，", "", "", ""],
    ["小淳", "xiǎo chún", "Xiaochun", "Xiaochun"],
    ["帮忙", "bāng máng", "helped", "tolong"],
    ["买菜做饭", "mǎi cài zuò fàn", "shop and cook", "beli sayur dan masak"],
    ["，", "", "", ""],
    ["使", "shǐ", "so that", "membuat"],
    ["妈妈", "mā ma", "mom", "ibu"],
    ["可以", "kě yǐ", "can", "boleh"],
    ["安心", "ān xīn", "peacefully", "dengan tenang"],
    ["工作", "gōng zuò", "work", "bekerja"],
    ["，", "", "", ""],
    ["公司", "gōng sī", "the company", "syarikat"],
    ["发给", "fā gěi", "gave", "beri"],
    ["我", "wǒ", "me", "saya"],
    ["一份", "yí fèn", "a", "satu"],
    ["勤工奖", "qín gōng jiǎng", "diligent worker award", "anugerah pekerja rajin"],
    ["，", "", "", ""],
    ["因此", "yīn cǐ", "therefore", "oleh itu"],
    ["今天", "jīn tiān", "today", "hari ini"],
    ["就将", "jiù jiāng", "then", "lalu"],
    ["剩下的", "shèng xià de", "remaining", "baki"],
    ["部分", "bù fen", "part", "bahagian"],
    ["全部", "quán bù", "all", "semuanya"],
    ["缴完了", "jiǎo wán le", "paid off", "selesai bayar"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 13 段

    ["“", "", "", ""],
    ["妈", "mā", "Mom", "Ibu"],
    ["！", "", "", ""],
    ["哥哥", "gē ge", "Brother", "Abang"],
    ["！", "", "", ""],
    ["真是", "zhēn shì", "really", "sungguh"],
    ["太好了", "tài hǎo le", "wonderful", "bagusnya"],
    ["，", "", "", ""],
    ["不过", "bú guò", "but", "tetapi"],
    ["以后", "yǐ hòu", "from now on", "selepas ini"],
    ["请", "qǐng", "please", "tolong"],
    ["让", "ràng", "let", "biarkan"],
    ["小淳", "xiǎo chún", "Xiaochun", "Xiaochun"],
    ["继续", "jì xù", "continue", "terus"],
    ["做晚饭", "zuò wǎn fàn", "cook dinner", "masak malam"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["“", "", "", ""],
    ["妈", "mā", "Mom", "Ibu"],
    ["，", "", "", ""],
    ["其实", "qí shí", "actually", "sebenarnya"],
    ["小淳", "xiǎo chún", "Xiaochun", "Xiaochun"],
    ["和我", "hé wǒ", "and I", "dan saya"],
    ["有一个", "yǒu yī gè", "have a", "ada satu"],
    ["秘密", "mì mì", "secret", "rahsia"],
    ["，", "", "", ""],
    ["一直", "yì zhí", "all along", "selama ini"],
    ["都", "dōu", "never", "tidak"],
    ["没有", "méi yǒu", "haven't", "pernah"],
    ["跟", "gēn", "with", "kepada"],
    ["妈妈", "mā ma", "Mom", "ibu"],
    ["您说", "nín shuō", "tell you", "beritahu awak"],
    ["，", "", "", ""],
    ["那是", "nà shì", "that was", "iaitu"],
    ["……", "", "", ""],
    ["十一月", "shí yī yuè", "November", "November"],
    ["的", "de", "", ""],
    ["一个", "yí gè", "a", "satu"],
    ["礼拜天", "lǐ bài tiān", "Sunday", "Ahad"],
    ["，", "", "", ""],
    ["小淳", "xiǎo chún", "Xiaochun's", "Xiaochun"],
    ["的", "de", "", ""],
    ["学校", "xué xiào", "school", "sekolah"],
    ["通知", "tōng zhī", "notified", "memberitahu"],
    ["家长", "jiā zhǎng", "parents", "ibu bapa"],
    ["要去", "yào qù", "to", "hendak pergi"],
    ["参观", "cān guān", "observe", "melawat"],
    ["教学课程", "jiào xué kè chéng", "teaching session", "sesi pengajaran"],
    ["，", "", "", ""],
    ["小淳的", "xiǎo chún de", "Xiaochun's", "Xiaochun"],
    ["老师", "lǎo shī", "teacher", "guru"],
    ["还", "hái", "also", "juga"],
    ["特别", "tè bié", "specially", "terutamanya"],
    ["附了", "fù le", "attached", "sertakan"],
    ["一封信", "yī fēng xìn", "a letter", "sehelai surat"],
    ["，", "", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["小淳的", "xiǎo chún de", "Xiaochun's", "Xiaochun"],
    ["一篇", "yī piān", "an essay", "sebuah karangan"],
    ["文章", "wén zhāng", "essay", "karangan"],
    ["被选为", "bèi xuǎn wéi", "was selected as", "dipilih sebagai"],
    ["全北海道", "quán běi hǎi dào", "all Hokkaido", "seluruh Hokkaido"],
    ["的", "de", "", ""],
    ["代表", "dài biǎo", "representative", "wakil"],
    ["，", "", "", ""],
    ["将", "jiāng", "will", "akan"],
    ["参加", "cān jiā", "participate in", "menyertai"],
    ["全国", "quán guó", "national", "kebangsaan"],
    ["的", "de", "", ""],
    ["作文比赛", "zuò wén bǐ sài", "essay competition", "pertandingan karangan"],
    ["。", "", "", ""],
    ["因此", "yīn cǐ", "therefore", "oleh itu"],
    ["那一天", "nà yī tiān", "that day", "hari itu"],
    ["我", "wǒ", "I", "saya"],
    ["代表", "dài biǎo", "represented", "mewakili"],
    ["妈去参观了", "mā qù cān guān le", "went to observe", "pergi melawat"],
    ["，", "", "", ""],
    ["老师", "lǎo shī", "the teacher", "guru"],
    ["出的", "chū de", "given", "memberi"],
    ["题目", "tí mù", "topic", "tajuk"],
    ["是", "shì", "is", "ialah"],
    ["《", "", "", ""],
    ["我的志愿", "wǒ de zhì yuàn", "My Ambition", "Cita-cita Saya"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["小淳", "xiǎo chún", "Xiaochun", "Xiaochun"],
    ["以", "yǐ", "with", "dengan"],
    ["一碗汤面", "yī wǎn tāng miàn", "A Bowl of Noodle Soup", "Semangkuk Mi Sup"],
    ["为", "wéi", "as", "sebagai"],
    ["题", "tí", "topic", "tajuk"],
    ["。", "", "", ""],
    ["作文", "zuò wén", "The essay", "Karangan"],
    ["是", "shì", "was", "ialah"],
    ["这样", "zhè yàng", "like this", "begini"],
    ["写的", "xiě de", "written", "ditulis"],
    ["：", "", "", ""],
    ["爸爸", "bà ba", "Dad", "Ayah"],
    ["车祸了", "chē huò le", "had a car accident", "kemalangan jalan raya"],
    ["，", "", "", ""],
    ["留下", "liú xià", "left", "meninggalkan"],
    ["很多", "hěn duō", "many", "banyak"],
    ["债务", "zhài wù", "debts", "hutang"],
    ["。", "", "", ""],
    ["为了", "wèi le", "In order to", "Untuk"],
    ["还债", "huán zhài", "repay debts", "bayar hutang"],
    ["，", "", "", ""],
    ["妈妈", "mā ma", "Mom", "Ibu"],
    ["从早到晚", "cóng zǎo dào wǎn", "from morning till night", "dari pagi hingga malam"],
    ["拼命", "pīn mìng", "worked hard", "bekerja keras"],
    ["工作", "gōng zuò", "work", "bekerja"],
    ["，", "", "", ""],
    ["哥哥", "gē ge", "brother", "abang"],
    ["每天", "měi tiān", "every day", "setiap hari"],
    ["早晚", "zǎo wǎn", "morning and evening", "pagi dan malam"],
    ["认真", "rèn zhēn", "diligently", "dengan tekun"],
    ["送报", "sòng bào", "delivers newspapers", "hantar surat khabar"],
    ["……", "", "", ""],
    ["十二月三十一日", "shí èr yuè sān shí yī rì", "December 31st", "31 Disember"],
    ["晚上", "wǎn shàng", "evening", "malam"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["母子三人", "mǔ zǐ sān rén", "mother and two sons", "ibu dan dua anak"],
    ["共同", "gòng tóng", "together", "bersama-sama"],
    ["吃", "chī", "eat", "makan"],
    ["一碗汤面", "yī wǎn tāng miàn", "one bowl of noodle soup", "semangkuk mi sup"],
    ["，", "", "", ""],
    ["非常", "fēi cháng", "very", "sangat"],
    ["好吃", "hǎo chī", "delicious", "sedap"],
    ["……", "", "", ""],
    ["三个人", "sān gè rén", "Three people", "Tiga orang"],
    ["只叫", "zhǐ jiào", "only ordered", "hanya pesan"],
    ["一碗汤面", "yī wǎn tāng miàn", "one bowl of noodle soup", "semangkuk mi sup"],
    ["，", "", "", ""],
    ["面店的", "miàn diàn de", "noodle shop's", "kedai mi"],
    ["伯伯", "bó bo", "uncle", "pakcik"],
    ["和", "hé", "and", "dan"],
    ["伯母", "bó mǔ", "auntie", "makcik"],
    ["竟然还", "jìng rán hái", "actually", "malahan"],
    ["向", "xiàng", "to", "kepada"],
    ["我们", "wǒ men", "us", "kita"],
    ["道谢", "dào xiè", "thanked us", "berterima kasih"],
    ["，", "", "", ""],
    ["并且", "bìng qiě", "and", "dan"],
    ["祝", "zhù", "wished", "mendoakan"],
    ["我们", "wǒ men", "us", "kita"],
    ["新年快乐", "xīn nián kuài lè", "Happy New Year", "Selamat Tahun Baru"],
    ["！", "", "", ""],
    ["那声音", "nà shēng yīn", "That voice", "Suara itu"],
    ["好像", "hǎo xiàng", "as if", "seolah-olah"],
    ["在", "zài", "was", "sedang"],
    ["鼓励", "gǔ lì", "encouraging", "memberi semangat"],
    ["我们", "wǒ men", "us", "kita"],
    ["要", "yào", "to", "untuk"],
    ["坚强勇敢地", "jiān qiáng yǒng gǎn de", "be strong and brave", "tabah dan berani"],
    ["活下去", "huó xià qù", "live on", "terus hidup"],
    ["，", "", "", ""],
    ["赶紧", "gǎn jǐn", "quickly", "segera"],
    ["把", "bǎ", "to", "untuk"],
    ["爸爸", "bà ba", "Dad's", "ayah"],
    ["留下的", "liú xià de", "left behind", "yang ditinggalkan"],
    ["债务", "zhài wù", "debts", "hutang"],
    ["还清", "huán qīng", "pay off", "langsaikan"],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 14 段

    ["“", "", "", ""],
    ["妈", "mā", "Mom", "Ibu"],
    ["，", "", "", ""],
    ["哥哥", "gē ge", "Brother", "Abang"],
    ["，", "", "", ""],
    ["小淳", "xiǎo chún", "Xiaochun", "Xiaochun"],
    ["决定", "jué dìng", "has decided", "telah memutuskan"],
    ["长大后", "zhǎng dà hòu", "when he grows up", "selepas dewasa"],
    ["要", "yào", "to", "hendak"],
    ["开面馆", "kāi miàn guǎn", "open a noodle shop", "buka kedai mi"],
    ["，", "", "", ""],
    ["要对", "yào duì", "to", "kepada"],
    ["每个", "měi gè", "every", "setiap"],
    ["客人", "kè rén", "customer", "pelanggan"],
    ["说", "shuō", "say", "berkata"],
    ["‘", "", "", ""],
    ["加油", "jiā yóu", "Keep going", "Teruskan"],
    ["！", "", "", ""],
    ["祝你幸福", "zhù nǐ xìng fú", "Wish you happiness", "Semoga bahagia"],
    ["！", "", "", ""],
    ["谢谢你", "xiè xie nǐ", "Thank you", "Terima kasih"],
    ["！", "", "", ""],
    ["’", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 15 段

    ["一直", "yì zhí", "All along", "Selama ini"],
    ["站在", "zhàn zài", "standing", "berdiri di"],
    ["厨台里", "chú tái lǐ", "inside the kitchen", "di dalam dapur"],
    ["听", "tīng", "listening", "mendengar"],
    ["他们", "tā men", "their", "mereka punya"],
    ["对话", "duì huà", "conversation", "perbualan"],
    ["的", "de", "", ""],
    ["老板夫妇", "lǎo bǎn fū fù", "boss and his wife", "pasangan tuan kedai"],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["失去", "shī qù", "disappeared from", "hilang dari"],
    ["踪影", "zōng yǐng", "sight", "pandangan"],
    ["，", "", "", ""],
    ["原来", "yuán lái", "it turned out", "rupanya"],
    ["他们", "tā men", "they", "mereka"],
    ["蹲下来", "dūn xià lái", "squatted down", "mencangkung"],
    ["，", "", "", ""],
    ["一条毛巾", "yī tiáo máo jīn", "a towel", "sehelai tuala"],
    ["一人抓一头", "yī rén zhuā yī tóu", "each holding one end", "masing-masing pegang satu hujung"],
    ["，", "", "", ""],
    ["拼命", "pīn mìng", "frantically", "dengan keras"],
    ["擦着", "cā zhe", "wiping", "menyapu"],
    ["不断", "bù duàn", "continuously", "tanpa henti"],
    ["涌出来的", "yǒng chū lái de", "welling up", "yang mengalir keluar"],
    ["泪水", "lèi shuǐ", "tears", "air mata"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["原文", "yuán wén", "Original text", "Teks asal"],
    ["取自", "qǔ zì", "taken from", "diambil dari"],
    ["网络", "wǎng luò", "online", "internet"],
    ["《", "", "", ""],
    ["一碗汤面", "yī wǎn tāng miàn", "A Bowl of Noodle Soup", "Semangkuk Mi Sup"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
